# Generated by Django 3.2 on 2023-01-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20230128_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='conv_starter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_replies', to='tweets.tweet'),
        ),
    ]
