# Generated by Django 3.2 on 2023-01-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_conv_starter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='conv_starter',
            new_name='branch_start',
        ),
    ]
