# Generated by Django 3.2 on 2023-01-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profiles_profile_followers_+', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reading',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profiles_profile_reading_+', to='profiles.Profile'),
        ),
    ]
