# Generated by Django 3.2 on 2023-02-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230131_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_who', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reading',
            field=models.ManyToManyField(blank=True, related_name='reading_whom', to='profiles.Profile'),
        ),
    ]
